Feature: Use threading.locks
bit-bots/bitbots_vision pull request #219
Opened 2020-03-17 12:04 UTC by JanGut

## Proposed changes
Use `threading.Lock()` in

- [x] `vision.py`
- [x] `dyanmic_color_space.py`
- [ ] `color.py`

## Related issues
Closes #90.
Closes #212.

## Necessary checks
- [ ] Update package version
- [ ] Run `catkin build`
- [ ] Write documentation
- [X] Create issues for future work
- [X] Test on your machine
- [ ] Test on the robot
- [X] Put the PR on our Project board

2020-03-17 13:25 UTC, JanGut commented on bitbots_vision/src/bitbots_vision/dynamic_color_space.py
> +                self._transfer_reconfigure_data = msg
```suggestion
        with self._transfer_reconfigure_data_mutex:
            # Set data
            self._transfer_reconfigure_data = msg
```

2020-03-17 13:30 UTC, JanGut commented on bitbots_vision/src/bitbots_vision/dynamic_color_space.py
> +                self._transfer_image_msg = image_msg
```suggestion
        with self._transfer_image_msg_mutex:
            # Transfer the image to the main thread
            self._transfer_image_msg = image_msg
```

2020-03-17 13:32 UTC, JanGut commented on bitbots_vision/src/bitbots_vision/dynamic_color_space.py
> +        if not rospy.is_shutdown():
skip, if locked...

2020-12-04 18:35 UTC, jaagut commented
Have a look at #248

2021-02-25 15:45 UTC, Flova requested changes

2021-02-25 15:45 UTC, Flova commented on bitbots_vision/src/bitbots_vision/vision_modules/color.py
> +                    data = _transfer_color_lookup_table_data
data is not necessary

2021-02-25 15:45 UTC, Flova commented on bitbots_vision/src/bitbots_vision/vision_modules/color.py
> +            # Lookup if there is another color lookup table available
This whole part is not needed

2021-02-25 15:45 UTC, Flova commented on bitbots_vision/src/bitbots_vision/vision_modules/color.py
> +        global _transfer_color_lookup_table_data
Add return if thread is locked

2021-02-25 16:58 UTC, Flova approved these changes

2021-02-25 16:59 UTC, merged