Evaluator
bit-bots/bitbots_vision pull request #221
Opened 2020-03-27 22:20 UTC by Flova

## Proposed changes
- Bring evaluator to the main branch
- Merge 1000 commits (not joking)
- Fix stuff
- Refactor stuff

## Necessary checks
- [ ] Update package version
- [x] Run `catkin build`
- [ ] Write documentation
- [ ] Create issues for future work
- [x] Test on your machine
- [ ] Test on the robot
- [x] Put the PR on our Project board

2020-03-28 07:46 UTC, NFiedler commented
Where are the original commits? :(

2020-03-28 15:45 UTC, Flova commented
I tried to transfer them, but sadly its lost while doing `git checkout branch file`. I hope your don't mind it. A simple merge was also not really possible, because the whole folder structure changed singe then.

2020-03-30 12:18 UTC, JanGut commented on bitbots_vision/launch/evaluator.launch
> +    <arg name="listen_field_boundary" doc="listen for horizon messages" default="true" />
```suggestion
    <arg name="listen_field_boundary" doc="listen for field boundary messages" default="true" />
```

2020-10-21 14:43 UTC, JanGut commented
@Flova Is this still a work in progress or is it ready to review?

2020-10-21 14:56 UTC, Flova commented
This is a draft which needs quite some work. Maybe I'll finish it at a future coding weekly.

2020-11-30 12:04 UTC, SammyRamone requested changes

2020-11-30 12:04 UTC, SammyRamone commented on bitbots_vision/scripts/evaluator.py
> +        # TODO maybe the message sequence could be used here
todos should not be commited to master but made into issues

2020-11-30 12:04 UTC, SammyRamone commented on bitbots_vision/scripts/evaluator.py
> +                # Hacks stuff for obstacles # TODO redo
todo

2020-12-01 12:34 UTC, Flova commented on bitbots_vision/config/evaluator_params.yaml
> +image_publish_topic: '/image_raw'
Yes and no. I think the pr isn't merged yet.

2020-12-01 12:57 UTC, SammyRamone commented on bitbots_vision/config/evaluator_params.yaml
> +image_publish_topic: '/image_raw'
then add this change to the other PR, that would probably be the cleanest approach

2020-12-01 14:36 UTC, Flova commented on bitbots_vision/config/evaluator_params.yaml
> +image_publish_topic: '/image_raw'
Yes but this needs to be merged first because the other PR does not include these files yet.

2020-12-03 13:41 UTC, jaagut commented on bitbots_vision/scripts/evaluator.py
> +            points = np.array(vektor, np.int32).reshape((-1,1,2))
```suggestion
        for vector in vectors:
            points = np.array(vector, np.int32).reshape((-1,1,2))
```

2020-12-03 15:47 UTC, SammyRamone approved these changes

2020-12-03 17:24 UTC, merged

2020-12-03 18:21 UTC, jaagut requested changes

2020-12-03 18:21 UTC, jaagut commented on bitbots_vision/scripts/evaluator.py
> +        This is set up to work with the "evaluation" export format of the Bit-Bots Team in the ImageTagger.
I suggest providing an demo-file to understand the structure (especially for non imagetagger users)

2020-12-03 18:21 UTC, jaagut commented on bitbots_vision/scripts/evaluator.py
> +    def _balls_callback(self, msg):
All of these callbacks have a lot of duplicated code... This should be refactored or at least create an issue

2020-12-11 15:43 UTC, jaagut commented
The missing issues will be addressed in #252.