bitbots_vision: Limit dyn colorspace rate
bit-bots/bitbots_vision pull request #248
Opened 2020-11-26 17:48 UTC by jaagut

## Proposed changes
This PR ratelimits the dynamic color space node using a new `dynamic_color_space_max_fps` parameter.

## Related issues
Closes #246.

## Necessary checks
- [ ] Update package version
- [x] Run `catkin build`
- [x] Write documentation
~- [ ] Create issues for future work~
- [x] Test on your machine
~- [ ] Test on the robot~
- [x] Put the PR on our Project board

2020-11-26 18:21 UTC, Flova approved these changes

2020-11-27 08:26 UTC, SammyRamone requested changes
please use rospy.Rate() instead. this makes it much more readable and does not require additional class variables
Edit: never mind you are working in the callback, there it does not work

2020-11-27 08:28 UTC, SammyRamone approved these changes

2020-11-28 14:26 UTC, jaagut commented
@SammyRamone Yeah, at first I tried implementing it using `rospy.Rate` and then noticed this issue. But after #219 is merged, we could do this.

2020-11-28 14:32 UTC, merged